In [5]:
import transformers
# from transformers import *
import numpy as np
import torch

In [6]:
name = 'facebook/bart-base'
generator = transformers.BartForConditionalGeneration.from_pretrained(name)
tokenizer = transformers.BartTokenizer.from_pretrained(name)


loading configuration file config.json from cache at /Users/jstav/.cache/huggingface/hub/models--facebook--bart-base/snapshots/aadd2ab0ae0c8268c7c9693540e9904811f36177/config.json
Model config BartConfig {
  "_name_or_path": "bart-base",
  "activation_dropout": 0.1,
  "activation_function": "gelu",
  "add_bias_logits": false,
  "add_final_layer_norm": false,
  "architectures": [
    "BartModel"
  ],
  "attention_dropout": 0.1,
  "bos_token_id": 0,
  "classif_dropout": 0.1,
  "classifier_dropout": 0.0,
  "d_model": 768,
  "decoder_attention_heads": 12,
  "decoder_ffn_dim": 3072,
  "decoder_layerdrop": 0.0,
  "decoder_layers": 6,
  "decoder_start_token_id": 2,
  "dropout": 0.1,
  "early_stopping": true,
  "encoder_attention_heads": 12,
  "encoder_ffn_dim": 3072,
  "encoder_layerdrop": 0.0,
  "encoder_layers": 6,
  "eos_token_id": 2,
  "forced_bos_token_id": 0,
  "forced_eos_token_id": 2,
  "gradient_checkpointing": false,
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1",
    "2": "

In [85]:
# model: gpt2
tokenizer = transformers.GPT2Tokenizer.from_pretrained('gpt2')
generator = transformers.GPT2LMHeadModel.from_pretrained('gpt2')

loading file vocab.json from cache at /Users/jstav/.cache/huggingface/hub/models--gpt2/snapshots/e7da7f221d5bf496a48136c0cd264e630fe9fcc8/vocab.json
loading file merges.txt from cache at /Users/jstav/.cache/huggingface/hub/models--gpt2/snapshots/e7da7f221d5bf496a48136c0cd264e630fe9fcc8/merges.txt
loading file added_tokens.json from cache at None
loading file special_tokens_map.json from cache at None
loading file tokenizer_config.json from cache at None
loading configuration file config.json from cache at /Users/jstav/.cache/huggingface/hub/models--gpt2/snapshots/e7da7f221d5bf496a48136c0cd264e630fe9fcc8/config.json
Model config GPT2Config {
  "_name_or_path": "gpt2",
  "activation_function": "gelu_new",
  "architectures": [
    "GPT2LMHeadModel"
  ],
  "attn_pdrop": 0.1,
  "bos_token_id": 50256,
  "embd_pdrop": 0.1,
  "eos_token_id": 50256,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "model_type": "gpt2",
  "n_ctx": 1024,
  "n_embd": 768,
  "n_head": 12,
  "n_inner": 

In [7]:
# prompt
prompt = "The dog ate a <mask> and enjoyed it greatly"
input_ids = tokenizer.encode(prompt, return_tensors='pt')


In [8]:
# embeddings
embed_matrix = generator.get_input_embeddings()
embeddings = embed_matrix(input_ids)

In [9]:
# chooses input_embeds
inputs_embeds = embeddings

In [10]:
attention_mask = torch.ones(inputs_embeds.shape[:2], dtype=torch.long)
decoder_input_ids = torch.ones((inputs_embeds.shape[0], 1), dtype=torch.long)*generator.config.decoder_start_token_id
output_ids = generator.generate(attention_mask=attention_mask, decoder_input_ids=decoder_input_ids, inputs_embeds=inputs_embeds)

Generate config GenerationConfig {
  "_from_model_config": true,
  "bos_token_id": 0,
  "decoder_start_token_id": 2,
  "early_stopping": true,
  "eos_token_id": 2,
  "forced_bos_token_id": 0,
  "forced_eos_token_id": 2,
  "no_repeat_ngram_size": 3,
  "num_beams": 4,
  "pad_token_id": 1,
  "transformers_version": "4.29.2"
}

/Users/jstav/anaconda3/envs/ccs/lib/python3.11/site-packages/transformers/generation/utils.py:1346: UserWarning: Using `max_length`'s default (20) to control the generation length. This behaviour is deprecated and will be removed from the config in v5 of Transformers -- we recommend using `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(


In [11]:
print(input_ids, "\n", output_ids)

tensor([[    0,   133,  2335, 14964,    10, 50264,     8,  3776,    24,  8908,
             2]]) 
 tensor([[    2,     0,   133,  2335, 14964,    10,   319,     9,   689,     8,
          3776,    24,  8908,     2]])


In [17]:
# display output
tokenizer.decode(output_ids[0], skip_special_tokens=True)

'The dog ate a lot of food and enjoyed it greatly'

In [12]:
# generates output?!
output = generator(attention_mask=attention_mask, decoder_input_ids=decoder_input_ids, inputs_embeds=inputs_embeds)

In [14]:
output

Seq2SeqLMOutput(loss=None, logits=tensor([[[34.0231,  7.1280, 15.8088,  ...,  6.8357,  6.7118,  1.5922]]],
       grad_fn=<AddBackward0>), past_key_values=((tensor([[[[-1.1472e-01, -5.2203e-01, -6.7271e-01, -2.3444e-01,  1.0991e-01,
            3.9414e-01, -1.9081e-01, -7.9089e-02, -9.5895e-01, -7.9138e-01,
            7.0146e-01,  3.0461e-01, -3.1922e+00,  2.8190e-01,  5.4080e-03,
           -7.2945e-02,  7.0916e-01,  2.6721e-02,  2.9459e-02, -3.0121e-01,
           -1.4141e+00,  3.2893e-01,  2.0117e-01,  9.8483e-02, -2.3897e-01,
            4.6142e-01,  5.6111e-01,  1.7983e-02, -4.7429e-01,  4.9782e-01,
           -3.7811e-02, -5.4314e-01,  6.6647e-01,  7.6226e-01,  1.9572e+00,
           -2.0149e-01, -1.1002e-02, -3.0611e-01, -5.1063e-01, -7.7412e-01,
           -6.0594e-02,  2.4726e-01, -4.6939e-02,  7.0074e-01, -8.9133e-01,
           -4.8659e-01,  1.6108e-01,  8.0704e-01,  4.5971e-01, -8.3734e-02,
            5.4333e-01, -8.3701e-01,  3.4535e-01,  3.0597e-02,  7.7793e-01,
       

In [15]:
# samples next 10 tokens from output logits
logits = output.logits
next_token_logits = logits[:, -1, :]
next_token = torch.argmax(next_token_logits, dim=-1)
print(next_token)

tensor([0])
